# Generated by Django 4.2.9 on 2024-02-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_token_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
