# Generated by Django 4.2.9 on 2024-02-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_rename_brand_id_carmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='logo_url',
            field=models.URLField(default='https://example.com/default_logo.png'),
        ),
    ]
