# Generated by Django 4.2.9 on 2024-02-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_carmodel_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='logo_url',
        ),
    ]
