# Generated by Django 4.2.9 on 2024-02-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_remove_carmodel_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='Brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.carbrand'),
        ),
    ]
