# Generated by Django 5.0.2 on 2024-02-22 13:08

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_alter_carmodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Variant_Name', models.CharField(max_length=100)),
                ('Fuel_Type', models.CharField(max_length=50)),
                ('Launch_Year', models.IntegerField()),
                ('Model_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.carmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
