# Generated by Django 4.2.9 on 2024-02-22 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_alter_carmodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_by', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Location', models.CharField(max_length=100)),
                ('Brand_Name', models.CharField(max_length=100)),
                ('Model_Name', models.CharField(max_length=100)),
                ('Variant_Name', models.CharField(max_length=100)),
                ('MFD_Year', models.IntegerField(max_length=4)),
                ('KiloMeter', models.CharField(max_length=100)),
                ('Ownership', models.CharField(max_length=100)),
                ('When_ToSell', models.CharField(max_length=100)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.authuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
