# Generated by Django 4.2.9 on 2024-02-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_cardetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='MFD_Year',
            field=models.IntegerField(),
        ),
    ]
