# Generated by Django 4.2.9 on 2024-02-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_alter_cardetails_mfd_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='Brand',
            new_name='User',
        ),
    ]
