# Generated by Django 5.0.2 on 2024-02-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_carvariant'),
        ('Core', '0019_rename_brand_cardetails_user'),
    ]

    operations = [
    ]
