# Generated by Django 4.2.9 on 2024-02-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_carvariant'),
        ('Core', '0019_rename_brand_cardetails_user'),
    ]

    operations = [
    ]
