# Generated by Django 4.2.9 on 2024-02-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_merge_20240222_1910'),
        ('Core', '0020_merge_20240223_1129'),
    ]

    operations = [
    ]
