# Generated by Django 4.2.9 on 2024-03-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_carimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='FuelType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='Seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='Transmission',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='caroverview',
            name='FuelType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='caroverview',
            name='Seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caroverview',
            name='Transmission',
            field=models.CharField(default='', max_length=100),
        ),
    ]
