# Generated by Django 5.0.2 on 2024-03-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_cardetails_fueltype_cardetails_seats_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarImages',
            new_name='CarImage',
        ),
    ]
