# Generated by Django 4.2.9 on 2024-03-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_remove_features_transmission_carvariant_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='Seats',
        ),
    ]
