# Generated by Django 4.2.9 on 2024-03-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_rename_carimages_carimage'),
        ('Core', '0030_alter_cardetails_fueltype_and_more'),
    ]

    operations = [
    ]
