# Generated by Django 4.2.9 on 2024-03-06 11:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_merge_20240306_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroverview',
            name='Image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
